name: gptapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  crypto: ^3.0.0
  shared_preferences: ^2.0.15
  google_sign_in: ^6.0.0
  flutter_facebook_auth: ^7.1.1
  firebase_crashlytics: ^4.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - Asset/images/logo.png
